// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKU9cVrCPFwX1M9ZP9q-0lKY9QfttBUDo',
    appId: '1:873347679538:web:b49b7e4591b865751b832b',
    messagingSenderId: '873347679538',
    projectId: 'farm-fresh-1',
    authDomain: 'farm-fresh-1.firebaseapp.com',
    storageBucket: 'farm-fresh-1.firebasestorage.app',
    measurementId: 'G-9DJGLDPX92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIZ4HewBvDFqtf2H5Rh9tf3_jxpo4epQE',
    appId: '1:873347679538:android:d58bcc273497e6721b832b',
    messagingSenderId: '873347679538',
    projectId: 'farm-fresh-1',
    storageBucket: 'farm-fresh-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9GgNLIbKyPsAQ_GkZUR9HitkAnJX8IeY',
    appId: '1:873347679538:ios:db89f922a514c06f1b832b',
    messagingSenderId: '873347679538',
    projectId: 'farm-fresh-1',
    storageBucket: 'farm-fresh-1.firebasestorage.app',
    iosBundleId: 'com.example.farmfresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9GgNLIbKyPsAQ_GkZUR9HitkAnJX8IeY',
    appId: '1:873347679538:ios:db89f922a514c06f1b832b',
    messagingSenderId: '873347679538',
    projectId: 'farm-fresh-1',
    storageBucket: 'farm-fresh-1.firebasestorage.app',
    iosBundleId: 'com.example.farmfresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKU9cVrCPFwX1M9ZP9q-0lKY9QfttBUDo',
    appId: '1:873347679538:web:2229a6fd0cf4a2951b832b',
    messagingSenderId: '873347679538',
    projectId: 'farm-fresh-1',
    authDomain: 'farm-fresh-1.firebaseapp.com',
    storageBucket: 'farm-fresh-1.firebasestorage.app',
    measurementId: 'G-HDD68G5VHB',
  );
}
